# Add otel sidecar
# annotations:
#   sidecar.opentelemetry.io/inject: "true"
#   instrumentation.opentelemetry.io/inject-java: "true"

apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: example-jenkins
  namespace: "{{ jenkins_namespace }}"
spec:
  configurationAsCode:
    configurations:
    - name: jenkins-operator-configuration
    secret:
      name: ""
  groovyScripts:
    configurations: []
    secret:
      name: ""
  jenkinsAPISettings:
    authorizationStrategy: createUser
  master:
    basePlugins:
    - name: kubernetes
      version: "3706.vdfb_d599579f3"
    - name: workflow-job
      version: "1239.v71b_b_a_124a_725"
    - name: workflow-aggregator
      version: "590.v6a_d052e5a_a_b_5"
    - name: git
      version: "4.12.1"
    - name: job-dsl
      version: "1.81"
    - name: configuration-as-code
      version: "1512.vb_79d418d5fc8"
    - name: kubernetes-credentials-provider
      version: "1.196.va_55f5e31e3c2" 
    plugins:
    - name: opentelemetry
      version: "2.9.2"
    - name: ssh-slaves
      version: 2.846.v1b_70190624f5
    disableCSRFProtection: false
    containers:
      - name: jenkins-master
        image: jenkins/jenkins:2.366-alpine
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 12
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 100
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 80
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 1500m
            memory: 3Gi
          requests:
            cpu: "1"
            memory: 500Mi
  seedJobs:
    - id: jenkins-operator
      targets: "cicd/jobs/*.jenkins"
      description: "Jenkins Operator repository"
      repositoryBranch: master
      repositoryUrl: https://github.com/jenkinsci/kubernetes-operator.git
