apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-operator-configuration
  namespace: "{{ jenkins_namespace }}"
data:
  1-main.yaml: |
    jenkins:
      systemMessage: "System created by ansible with help of Margays"
      securityRealm:
        local:
          allowsSignup: false
          users:
            - id: "margay"
              password: "small@kitty"
      authorizationStrategy:
        loggedInUsersCanDoAnything:
          allowAnonymousRead: false
    unclassified:
      location:
        adminAddress: "adres jeszcze nie jest skonfigurowany <nobody@nowhere>"
        url: "http://localhost:8080/"
      openTelemetry:
        authentication: "noAuthentication"
        disabledResourceProviders: "io.opentelemetry.sdk.extension.resources.ProcessResourceProvider"
        endpoint: "http://otel-collector-collector.otel.svc.cluster.local:4317"
        exportOtelConfigurationAsEnvironmentVariables: false
        ignoredSteps: "dir,echo,isUnix,pwd,properties"
        serviceName: "jenkins"
        serviceNamespace: "jenkins"
        observabilityBackends:
        - elastic:
            displayKibanaDashboardLink: true
            kibanaBaseUrl: "https://kibana-kb-http.elastic.svc.cluster.local:5601"
            elasticLogsBackend: "elasticLogsBackendWithoutJenkinsVisualization"
