apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata: 
  name: system-kubernetes-agent
  namespace: "{{ elastic_namespace }}"
spec:
  version: "{{ elastic_stack_version }}"
  kibanaRef:
    name: kibana
  fleetServerRef: 
    name: fleet-server
  mode: fleet
  policyId: system-kubernetes-policy
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: system-kubernetes-agent
        hostNetwork: true
        dnsPolicy: ClusterFirstWithHostNet
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system-kubernetes-agent
rules:
- apiGroups: [""]
  resources:
  - pods
  - nodes
  - namespaces
  - events
  - services
  - configmaps
  verbs:
  - get
  - watch
  - list
- apiGroups: ["coordination.k8s.io"]
  resources:
  - leases
  verbs:
  - get
  - create
  - update
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get
- apiGroups: ["extensions"]
  resources:
    - replicasets
  verbs: 
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - "apps"
  resources:
  - statefulsets
  - deployments
  - replicasets
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - ""
  resources:
  - nodes/stats
  verbs:
  - get
- apiGroups:
  - "batch"
  resources:
  - jobs
  verbs:
  - "get"
  - "list"
  - "watch"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: system-kubernetes-agent
  namespace: "{{ elastic_namespace }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system-kubernetes-agent
subjects:
- kind: ServiceAccount
  name: system-kubernetes-agent
  namespace: "{{ elastic_namespace }}"
roleRef:
  kind: ClusterRole
  name: system-kubernetes-agent
  apiGroup: rbac.authorization.k8s.io