- name: Add nfs-subdir-external-provisioner repository
  kubernetes.core.helm_repository:
    name: nfs-subdir-external-provisioner
    repo_url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner

- name: Install nfs-subdir-external-provisioner
  kubernetes.core.helm:
    name: nfs-subdir-external-provisioner
    chart_ref: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    release_namespace: "{{ target_namespace }}"
    update_repo_cache: True
    wait: True
    atomic: True
    values:
      nfs:
        server: "{{ nfs_server }}"
        path: "{{ nfs_path }}"
      storageClass:
        onDelete: "{{ storageClass_onDelete }}"
