- name: Download Jenkins crds
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/config/crd/bases/jenkins.io_jenkins.yaml
    dest: ~/jenkins_crds.yml
    mode: '0664'

- name: Apply Jenkins crds
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    src: ~/jenkins_crds.yml

- name: Download Jenkins operator
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/deploy/all-in-one-v1alpha2.yaml
    dest: ~/jenkins_operator.yml
    mode: '0664'

- name: Create namespace for Jenkins instance
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    template: files/namespace.yml

- name: Create Jenkins operator
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    template: files/jenkins_operator.yml

- name: Create jenkins configuration resources
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    template: files/caas/jenkins_operator_configuration.yaml

- name: Deploy Jenkins instance
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    template: files/jenkins.yml
  tags:
  - jenkins
