- name: Create namespace for Jenkins instance
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    template: files/namespace.yml

- name: Add stable chart repo
  kubernetes.core.helm_repository:
    state: "{{ deployment_state }}" 
    name: jenkins
    repo_url: "https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/chart"

- name: Deploy jenkins-operator
  kubernetes.core.helm:
    state: "{{ deployment_state }}"
    name: jenkins-operator
    namespace: "{{ jenkins_namespace }}"
    chart_ref: jenkins/jenkins-operator
    chart_version: "{{ jenkins_chart_version }}"
    update_repo_cache: True
    wait: True
    atomic: True
    values:
      jenkins:
        enabled: false
        namespace: "{{ jenkins_namespace }}"
      operator:
        image: virtuslab/jenkins-operator:94b1473

- name: Create jenkins configuration resources
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    template: files/caas/jenkins_operator_configuration.yaml

- name: Deploy Jenkins instance
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    template: files/jenkins.yml
  tags:
  - jenkins
