---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elasticsearch-es-cert
  namespace: {{ elastic_namespace }}
spec:
  isCA: false
  dnsNames:
    - elasticsearch-es-http
    - elasticsearch-es-http.{{ elastic_namespace }}.svc
    - elasticsearch-es-http.{{ elastic_namespace }}.svc.cluster.local
  subject:
    organizations:
      - example
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-cluster-issuer
  secretName: elasticsearch-es-cert
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: {{ elastic_namespace }}
spec:
  version: "{{ elastic_stack_version }}"
  http:
    tls:
      certificate:
        secretName: elasticsearch-es-cert
  auth:
    fileRealm:
    - secretName: elastic-user-margay
  nodeSets:
  - name: default
    count: 3
    # volumeClaimTemplates:
    # - metadata:
    #     name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
    #   spec:
    #     accessModes:
    #     - ReadWriteOnce
    #     resources:
    #       requests:
    #         storage: 5Gi
    #     storageClassName: nfs-client
    config:
      node.store.allow_mmap: false
      xpack.monitoring.collection.enabled: true
