- name: Create namespace
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    template: files/namespace.yaml

- name: Create users secret
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    template: files/users_secret.yaml

- name: Create elastic cluster
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    template: files/elastic.yaml

- name: Create kibana
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    template: files/kibana.yaml

- name: Create Fleet
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    template: files/agents/fleet.yaml

- name: Create APM Agent
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    template: files/agents/apm.yaml

- name: Create System & Kubernetes Agent
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    template: files/agents/system_and_kubernetes.yaml
