- name: Add elastic chart repository
  kubernetes.core.helm_repository:
    state: "{{ deployment_state }}" 
    name: elastic
    repo_url: "https://helm.elastic.co"

- name: Deploy elastic operator
  kubernetes.core.helm:
    state: "{{ deployment_state }}"
    name: elastic-operator
    namespace: elastic-system
    create_namespace: True
    chart_ref: elastic/eck-operator
    chart_version: "{{ elastic_operator_version }}"
    update_repo_cache: True
    wait: True
    atomic: True

- name: Deploy Elastic cluster
  import_tasks: create_cluster.yml
