- name: Download Elastic crds
  ansible.builtin.get_url:
    url: https://download.elastic.co/downloads/eck/{{ elastic_operator_version }}/crds.yaml
    dest: ~/elastic_crds.yml
    mode: '0664'

- name: Apply Elastic crds
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    src: ~/elastic_crds.yml

- name: Download Elastic operator
  ansible.builtin.get_url:
    url: https://download.elastic.co/downloads/eck/{{ elastic_operator_version }}/operator.yaml
    dest: ~/elastic_operator.yml
    mode: '0664'

- name: Create Elastic operator
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    src: ~/elastic_operator.yml

- name: Deploy Elastic cluster
  import_tasks: create_cluster.yml
