- name: Create cert-manager namespace
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    src: namespace.yaml

- name: Add stable chart repo
  kubernetes.core.helm_repository:
    state: "{{ deployment_state }}" 
    name: jetstack
    repo_url: "https://charts.jetstack.io"

- name: Deploy cert-manager
  kubernetes.core.helm:
    state: "{{ deployment_state }}"
    name: cert-manager
    namespace: cert-manager
    chart_ref: jetstack/cert-manager
    chart_version: "{{ cert_manager_version }}"
    update_repo_cache: True
    wait: True
    atomic: True
    values:
      installCRDs: true

- name: Deploy cert-manager-trust
  kubernetes.core.helm:
    state: "{{ deployment_state }}"
    name: cert-manager-trust
    namespace: cert-manager
    chart_ref: jetstack/cert-manager-trust
    chart_version: "{{ cert_manager_trust_version }}"
    update_repo_cache: True
    wait: True
    atomic: True

- name: Create self-signed issuer
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    src: self_signed_issuer.yaml

- name: Create cluster internal cert bundle
  kubernetes.core.k8s:
    state: "{{ deployment_state }}"
    template:
      - path: 'files/trust_bundles/internal/ca.yaml'
      - path: 'files/trust_bundles/internal/bundle.yaml'
