---
- name: Install Elastic
  hosts: localhost
  vars:
    deployment_state: present
  roles:
  - facts/http_proxy
  - nfs-external-provisioner
  - cert-manager
  - elastic
  - open-telemetry
  - jenkins
